version: '3.8'

services:
  wopus-backend:
    build:
      dockerfile: docker/backend/Dockerfile
    volumes:
      - ./backend:/var/www/html
    environment:
      DB_HOST: wopus-mysql
      DB_USERNAME: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    ports:
      - 8000:8000
    depends_on:
      - wopus-mysql

  wopus-front:
    image: node:20
    user: node
    restart: unless-stopped
    container_name: wopus_front
    working_dir: /home/node/app
    command: sh -c 'npm install && npm run start'
    volumes:
      - ./frontend:/home/node/app/:Z
    ports:
      - 3000:3000

  wopus-mysql:
    restart: unless-stopped
    image: mysql
    container_name: wopus_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql:Z

  wopus-phpmyadmin:
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin
    container_name: wopus_pma
    links:
      - wopus-mysql
    ports:
      - 8081:8080
    environment:
      PMA_HOST: wopus-mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
      PMA_ABSOLUTE_URI: https://localhost:8081

volumes:
  mysql-data: {}
